// Generated by dts-bundle v0.7.3
// Dependencies for this module:
//   ../../../../packages/inferno-create-class/inferno-component

declare module 'inferno-create-class' {
    /**
        * @module Inferno-Create-Class
        */ /** TypeDoc Comment */
    import Component, { ComponentLifecycle } from "inferno-component";
    export interface Mixin<P, S> extends ComponentLifecycle<P, S> {
            statics?: {
                    [key: string]: any;
            };
            mixins?: any;
            displayName?: string;
            propTypes?: {
                    [index: string]: Function;
            };
            getDefaultProps?(): P;
            getInitialState?(): S;
    }
    export interface ComponentClass<P, S> extends Mixin<P, S> {
            new (props?: P, context?: any): Component<P, S>;
            propTypes?: {};
            contextTypes?: {};
            childContextTypes?: {};
            defaultProps?: P;
            displayName?: string;
    }
    export interface ComponentSpec<P, S> extends Mixin<P, S> {
            [propertyName: string]: any;
            render(props?: any, context?: any): any;
    }
    export interface ClassicComponent<P, S> extends Component<P, S> {
            replaceState(nextState: S, callback?: () => any): void;
            isMounted(): boolean;
            getInitialState?(): S;
    }
    export interface ClassicComponentClass<P, S> extends ComponentClass<P, S> {
            new (props?: P, context?: any): ClassicComponent<P, S>;
            getDefaultProps?(): P;
    }
    export default function createClass<P, S>(obj: ComponentSpec<P, S>): ClassicComponentClass<P, S>;
}

